services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - 'dev.env'
    ports:
      - '127.0.0.1:443:443'
      - '127.0.0.1:80:8080'
    extra_hosts:
        - "local.freelance-invoice-hub.com:127.0.0.1"
    volumes:
      - .:/app
      - freelance-invoice-hub_mod_cache:/go/pkg/mod

volumes:
  freelance-invoice-hub_mod_cache:
